name: Continuous integration
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      arangodb:
        image: arangodb:3.10.9
        env:
          ARANGO_ROOT_PASSWORD: rootpass
        ports:
          - 8529/tcp
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: set up golang
        uses: actions/setup-go@v5
        with:
          go-version: '~1.22'
      - run: go version
      - name: unit test
        run: go test -covermode=atomic -coverprofile=profile.cov -v ./...
        env:
          ARANGO_USER: root
          ARANGO_PASS: rootpass
          ARANGO_HOST: localhost
          ARANGO_PORT: ${{ job.services.arangodb.ports[8529] }}
          GOPROXY: https://proxy.golang.org
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./profile.cov
          token: ${{ secrets.CODECOV }}
  call-build-deploy:
    needs: test
    uses: dictyBase/workflows/.github/workflows/composite-deploy.yaml@main
    secrets: inherit
    with:
      app: order
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
      dockerfile: build/package/Dockerfile 
      docker_image: modware-order
      cluster: ${{ vars.DEV_STAGING_CLUSTER }}
      cluster_state_storage: ${{ vars.DEV_STAGING_KOPS_STATE_STORAGE }}
