name: Staging Build
on:
  push:
    branches:
      - staging
jobs:
  call-build-deploy:
    uses: dictyBase/workflows/.github/workflows/composite-deploy.yaml@main
    secrets: inherit
    with:
      app: order
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
      dockerfile: build/package/Dockerfile 
      docker_image: modware-order
      cluster: ${{ vars.DEV_STAGING_CLUSTER }}
      cluster_state_storage: ${{ vars.DEV_STAGING_KOPS_STATE_STORAGE }}
      stack: staging
      environment: staging
